--// This file was generated by 69ms using hookOp [https://discord.gg/yRrH6vHBCK]
--// Time taken: 1.454164299997501

-- Successfully sent http GET requests to the following site(s): 'https://raw.githubusercontent.com/Mangnex/Lunar-Hub/refs/heads/main/FreeLoader.lua'
local fenv = getfenv();
local eko1 = task.wait(1);
local eko2 = game.GetService;
local eko3 = game:GetService("CoreGui");
local success = pcall(function(p1, a, b, c)
    local eko4 = game.CoreGui.DescendantAdded;
    local eko5 = eko4.Connect;
    local eko6 = eko4:Connect(function(p1_0, a_0, b_0, c_0) end);
end);
local eko7 = game.GetService;
local eko8 = game:GetService("Players");
local eko9 = game.Players.LocalPlayer;
local eko10 = eko9.FindFirstChild;
local eko11 = eko9:FindFirstChild("PlayerGui");
local eko12 = eko9 and nil;
if eko12 then 
end;
local eko13 = task.wait(1.5);
local eko14 = game.GetService;
local eko15 = game:GetService("CoreGui");
local eko16 = game.CoreGui.GetDescendants;
local eko17 = game.CoreGui:GetDescendants();
for for_key_0, for_val_0 in ipairs(eko17) do
    local eko18 = {};
    local eko19 = eko18;
    local eko20 = eko19[for_val_0];
    local success_1 = pcall(function(a_2, b_2, c_2)
        local eko21 = for_val_0.IsA;
        local eko22 = for_val_0:IsA("TextLabel");
        local eko23 =         ;
        local eko24 = eko22 or eko23();
        local eko25 =         ;
        local eko26 = eko24 or eko25();
        if eko26 then 
            local eko27 = for_val_0.Text;
            local eko28 = (eko27 ~= "");
            local eko29 = eko27 and eko28;
            if eko29 then 
                local eko30 = not eko27;
                local eko31 = type(eko27);
                local eko32 = (eko31 ~= "string");
                local eko33 = eko30 or eko32;
                if eko33 then 
                    local eko34 = (eko27 ~= eko27);
                    if eko34 then 
                    end;
                end;
            end;
        end;
    end);
end;
local eko35 = game.GetService;
local eko36 = game:GetService("Players");
local eko37 = game.Players.LocalPlayer;
local eko38 = eko9.FindFirstChild;
local eko39 = eko9:FindFirstChild("PlayerGui");
local eko40 = eko9 and nil;
if eko40 then 
end;
local eko48 = eko47.Body;
local success_2 = pcall(function(a_3, b_3, c_3)
    local eko41 = game.HttpGet;
    local eko42 = game:HttpGet("https://raw.githubusercontent.com/Mangnex/Lunar-Hub/refs/heads/main/FreeLoader.lua");
    local eko43 = loadstring(eko42);
    local eko44 = game.PlaceId;
    local eko45 = (eko44 == 3431407618);
    if eko45 then 
        local eko46 = {
            ["Method"] = "GET",
            ["Url"] = "https://lunar-rest-api.vercel.app/script/Isle10"
        };
        local eko47 = request(eko46);
        local eko49 = eko47.Body;
        local eko50 = loadstring(eko49);
        local eko51 = eko50();
    end;
end);
local eko52 = not success_2;
if eko52 then 
end;